#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password: ""
#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#spring:
#                 h2:
#                   console:
#                     enabled: true

spring.datasource.url: jdbc:postgresql://localhost/postgres
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: postgres
spring.datasource.password: 123



spring:
  jpa:
    generate-ddl: true
  mustache:
    expose-request-attributes: true
  thymeleaf:
    enabled: false
